# Generated by Django 6.0.1 on 2026-01-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Monthly Contribution'), ('WITHDRAWAL', 'Savings Withdrawal'), ('FINE', 'Late Payment Fine'), ('SHARE_TRANSFER', 'Transfer to Share Capital'), ('BOND_INVESTMENT', 'Investment in Govt Bonds')], default='DEPOSIT', max_length=20),
        ),
    ]
